export enum GhTipoSesion {
  PRESENCIAL = 'PRESENCIAL',
  VIRTUAL = 'VIRTUAL',
  HIBRIDA = 'HIBRIDA',
}

export enum GhTipoCita {
  INDUCCION = 'INDUCCION',
  FIRMA_CONTRATO = 'FIRMA_CONTRATO',
  ENTREGA_DOTACION = 'ENTREGA_DOTACION',
  ENTREVISTA = 'ENTREVISTA',
}

export enum GhEstadoCita {
  PROGRAMADA = 'PROGRAMADA',
  CONFIRMADA = 'CONFIRMADA',
  EN_CURSO = 'EN_CURSO',
  FINALIZADA = 'FINALIZADA',
  NO_ASISTIO = 'NO_ASISTIO',
  CANCELADA = 'CANCELADA',
}

export enum GhImportacionEstado {
  PENDIENTE = 'PENDIENTE',
  PROCESANDO = 'PROCESANDO',
  COMPLETADA = 'COMPLETADA',
  FALLIDA = 'FALLIDA',
}

export enum GhTipoAcceso {
  ENTRADA = 'ENTRADA',
  SALIDA = 'SALIDA',
}

export enum GhEstadoSesionInduccion {
  PROGRAMADA = 'PROGRAMADA',
  EN_CURSO = 'EN_CURSO',
  FINALIZADA = 'FINALIZADA',
  CERRADA = 'CERRADA',
  CANCELADA = 'CANCELADA',
}

export enum GhEstadoAsistenciaInduccion {
  PENDIENTE = 'PENDIENTE',
  CHECKIN_OK = 'CHECKIN_OK',
  EN_SESION = 'EN_SESION',
  CHECKOUT_OK = 'CHECKOUT_OK',
  NO_ASISTIO = 'NO_ASISTIO',
  SALIDA_PENDIENTE = 'SALIDA_PENDIENTE',
}

export enum GhDotacionEntregaEstado {
  PENDIENTE = 'PENDIENTE',
  PARCIAL = 'PARCIAL',
  COMPLETA = 'COMPLETA',
  REPROGRAMADA = 'REPROGRAMADA',
  ANULADA = 'ANULADA',
}

export enum GhDotacionItemEstado {
  PENDIENTE = 'PENDIENTE',
  ENTREGADO = 'ENTREGADO',
  FALTANTE = 'FALTANTE',
}
